name: Build and push image

on:
  push:
    branches: [ master ]

  schedule:
    - cron: '0 0 * * Sun'

  workflow_dispatch:

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ github.repository }}:latest
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
